version: '3.8'
services:
  node16_build:
    #build:
        #context: .
        #dockerfile: node.Dockerfile
    image: node-16-aws-base:v1
    volumes:
      - .:/app
    working_dir: /app
    privileged: true
    networks: 
      - sharednetwork_build
networks:
  sharednetwork_build:
    name: sharednetwork_build